version: 2

updates:
  - package-ecosystem: npm
    directories:
      - /Electron/bug-logger
      - /Electron/image-shrink
      - /Electron/sys-top
    schedule:
      interval: weekly

    groups:
      non-major:
        update-types:
          - minor
          - patch

      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch

      major:
        update-types:
          - major