version: 2

updates:
  - package-ecosystem: npm
    directory: /Electron/bug-logger
    schedule:
      interval: weekly
    groups:
      dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /Electron/image-shrink
    schedule:
      interval: weekly
    groups:
      dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /Electron/sys-top
    schedule:
      interval: weekly
    groups:
      dependencies:
        update-types:
          - minor
          - patch